version: '2.1'
services:
  cinfomed-app:
    container_name: cinfomed-app
    image: luinal/cinfomed:app
    links:
      - cinfomed-db
    ports:
      - 8000:80
    volumes:
      - app_data:/var/www/html/
  cinfomed-db:
    container_name: cinfomed-db
    image: luinal/cinfomed:db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinfomed
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "9906:3306"
  phpmyadmin:
    container_name: cinfomed-phpmyadmin
    image: phpmyadmin 
    ports:
      - '8023:80'
    restart: always
    environment:
        PMA_HOST: cinfomed-db
    links:
      - cinfomed-db

volumes:
  mysql_data:
  app_data:
